# Docker Compose for Vehiculos Application
services:
  # Microsoft SQL Server 2022
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vehiculos-mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123" # Override via env / .env for production
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - vehiculos-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $${MSSQL_SA_PASSWORD} -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  # Node.js Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehiculos-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - vehiculos-network
    volumes:
      - ./logs:/app/logs # Optional: for logs if you add logging

# Named volumes
volumes:
  mssql_data:
    driver: local

# Networks
networks:
  vehiculos-network:
    driver: bridge
