export enum DocumentTypeEnum {
  DNI = "DNI",
  LICENSE = "LICENSE",
  VTV = "VTV",
  INSURANCE = "INSURANCE",
  VEHICLE_MANUAL = "VEHICLE_MANUAL",
  DRIVING_PERMIT = "DRIVING_PERMIT",
  PURCHASE_TICKET = "PURCHASE_TICKET",
}
