delete from vehicles;

insert into
    vehicles (
        license_plate,
        brand,
        model,
        year,
        img_url
    )
values (
        'JKL123',
        'Nissan',
        'Altima',
        2017,
        'https://s1.cdn.autoevolution.com/images/gallery/NISSANAltimaSedan-4744_6.jpg'
    ),
    (
        'MNO456',
        'Hyundai',
        'Elantra',
        2016,
        'https://s1.cdn.autoevolution.com/images/gallery/hyundai-elantra-2023-7583_27.jpg'
    ),
    (
        'PQR789',
        'Kia',
        'Optima',
        2015,
        'https://s1.cdn.autoevolution.com/images/gallery/KIA-K5-6868_32.jpg'
    ),
    (
        'STU012',
        'Mazda',
        '3',
        2014,
        'https://s1.cdn.autoevolution.com/images/gallery/MAZDA-3---Axela-Sedan-6446_5.jpg'
    ),
    (
        'VWX345',
        'Subaru',
        'Impreza',
        2013,
        'https://s1.cdn.autoevolution.com/images/gallery/subaru-impreza-5-doors-2022-7346_19.jpg'
    ),
    (
        'YZA678',
        'BMW',
        '3 Series',
        2012,
        'https://s1.cdn.autoevolution.com/images/gallery/bmw-3-series-sedan-2024-7754_8.jpg'
    ),
    (
        'BCD901',
        'Mercedes-Benz',
        'C-Class',
        2011,
        'https://s1.cdn.autoevolution.com/images/gallery/MERCEDES-BENZ-SLC-Class--R172--5698_24.jpg'
    ),
    (
        'EFG234',
        'Audi',
        'A4',
        2010,
        'https://s1.cdn.autoevolution.com/images/gallery/AUDI-A4-6631_15.jpg'
    ),
    (
        'HIJ567',
        'Lexus',
        'IS',
        2009,
        'https://s1.cdn.autoevolution.com/images/gallery/LEXUS-IS-6846_25.jpg'
    ),
    (
        'KLM890',
        'Acura',
        'TLX',
        2008,
        'https://s1.cdn.autoevolution.com/images/gallery/ACURA-TLX-6828_15.jpg'
    );